prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
  service:
    type: NodePort
grafana:
  enabled: true
  service:
    type: NodePort
  adminUser: admin
  adminPassword: password753
alertmanager:
  enabled: true
  service:
    type: NodePort
